#pragma once

#include <vine/robotics/robot_core_global.hpp>

#include <cstddef>
#include <filesystem>
#include <memory>
#include <vector>

#include <vine/String.hpp>
#include <vine/geometry/Material.hpp>
#include <vine/intrusive_ptr.hpp>
#include <vine/raw_ptr.hpp>
#include <vine/robotics/kinematics/Frame.hpp>
#include <vine/robotics/kinematics/KinematicsBase.hpp>
#include <vine/robotics/kinematics/Q.hpp>
#include <vine/robotics/kinematics/State.hpp>

#include "Joint.hpp"
#include "Link.hpp"
#include "SceneObject.hpp"

V_ROBOTICS_WORKCELL_NS_BEGIN

/**
 * @brief Kind of a device.
 */
enum class DeviceKind
{
    // 机械臂
    Manipulator = 1,
    // 外部轴
    ExternalAxis,
    // 变位机
    Positioner,
    // 扫描仪
    Scanner,
    // 工具
    Tool,
    // 其他类型
    Other = 255
};

/**
 * @brief Length unit of a device file's coordinates.
 *
 * The value is used as a scale-factor ratio: converting a length from unit A
 * to unit B multiplies by value(B) / value(A).
 */
enum class LengthUnit
{
    /// Meter.
    Meter = 1,
    /// Millimeter (in-memory default).
    Millimeter = 1000,
};

/**
 * @brief Device metadata (identity / product / version information).
 *
 * name is the original device name (not the instance name). Serialization
 * fields (timestamps, length unit, default IK solver) are carried here so
 * the IO layer can round-trip them.
 */
struct V_ROBOTICS_CORE_API DeviceMetadata
{
    // 身份信息
    String id;
    String name; // 设备原本名称(非实例名称)
    String description;
    String sn;
    // 产品信息
    String manufacturer;
    String model;
    // 作者
    String author;
    // 版本信息
    String version;
    // 序列化信息
    String                   create_time;
    String                   modified_time;
    LengthUnit               length_unit{ LengthUnit::Millimeter };
    kinematics::IKSolverType ik_solver_type{ kinematics::IKSolverType::Iterative };
};

/**
 * @brief A named material in a device's material library.
 *
 * Visuals reference device materials by name; the material object is shared
 * between the library and the referencing visuals.
 */
struct V_ROBOTICS_CORE_API DeviceMaterial
{
    /// Material name (unique within a device).
    String name;
    /// The material object.
    vine::intrusive_ptr<vine::geometry::Material> material;
};

/**
 * @brief Device definition data (immutable once handed to a device).
 *
 * Holds the link / joint definitions plus the metadata; a device can only be
 * configured from it. It is created by the caller (builder / loader) and
 * transferred to the device via Device::init, which takes ownership and
 * generates the intermediate data (link / joint views, ends, frame tree).
 *
 * Supports clone() for deep-copying the definition (e.g. one builder snapshot
 * per build()). Owns links and joints with unique ownership.
 */
struct V_ROBOTICS_CORE_API DeviceData
{
    DeviceMetadata                                  metadata;
    DeviceKind                                      kind{ DeviceKind::Other };
    /// Named material library; visuals reference these by name.
    std::vector<DeviceMaterial>                     materials;
    std::vector<std::unique_ptr<Link>>              links;
    std::vector<std::unique_ptr<Joint>>             joints;

    DeviceData() = default;
    // 独占所有权, 不可拷贝; 虚析构支持派生定义数据多态
    virtual ~DeviceData() = default;
    DeviceData(const DeviceData&)            = delete;
    DeviceData& operator=(const DeviceData&) = delete;
    DeviceData(DeviceData&&) noexcept        = default;
    DeviceData& operator=(DeviceData&&) noexcept = default;

    /**
     * @brief Creates a deep copy of the definition data.
     *
     * Links and joints are deep-copied; joints are rebound against the cloned
     * links.
     *
     * @return A new definition data object of the same type.
     */
    virtual std::unique_ptr<DeviceData> clone() const;

  protected:
    /**
     * @brief Copies the common part (metadata / links / joints), for derived
     *        clone() implementations.
     *
     * @param other The source definition data.
     */
    void copyBaseFrom(const DeviceData& other);
};

/**
 * @brief Base class of all devices in a workcell.
 *
 * A device is a scene-managed object composed of links and joints plus
 * multiple end frames. It inherits its base frame from SceneObject, and every
 * frame it carries (base + joints + ends) is registered in the SceneObject
 * frame registry as a raw pointer. Devices may be mounted on other devices
 * (e.g. a scanner on a robot's TCP) through a parent frame; the world pose
 * then cascades down the parent chain, so a child follows the parent's motion
 * automatically.
 *
 * Ownership:
 *  - The Workcell owns every device (unique ownership).
 *  - The device owns its definition data (DeviceData), which in turn owns the
 *    Link and Joint objects with unique ownership; links_ / joints_ / ends_
 *    are non-owning views generated by init().
 *  - A parent reference is a non-owning frame pointer; a parent must belong to
 *    the same Workcell and must outlive its children (the Workcell detaches
 *    children when a device is removed).
 */
class V_ROBOTICS_CORE_API Device : public SceneObject
{
  protected:
    /**
     * @brief Constructs an empty device; configure it with init().
     */
    Device() = default;

    /**
     * @brief Constructs a device with the given name.
     *
     * @param name The device name.
     */
    explicit Device(const String& name)
    {
        setName(name);
    }

  public:
    /**
     * @brief Destroys the device.
     */
    ~Device() override = default;

    /**
     * @brief Returns the object kind.
     *
     * @return SceneObjectKind::Device.
     */
    SceneObjectKind kind() const override
    {
        return SceneObjectKind::Device;
    }

    /**
     * @brief Returns the device kind (robot, scanner, ...).
     *
     * @return The kind.
     */
    DeviceKind deviceKind() const
    {
        return device_kind_;
    }

    /**
     * @brief Returns the model name (from the metadata).
     *
     * @return The model name, empty when the device is not initialized.
     */
    const String& modelName() const;

    /**
     * @brief Returns the source file path this device was loaded from.
     *
     * @return The source file path, empty when not loaded from a file.
     */
    const std::filesystem::path& filePath() const
    {
        return file_path_;
    }

    /**
     * @brief Sets the source file path this device was loaded from.
     *
     * Used by the IO layer to enable device-file dedup on export.
     *
     * @param path The source file path.
     */
    void setFilePath(const std::filesystem::path& path)
    {
        file_path_ = path;
    }

    /**
     * @brief Returns the device metadata.
     *
     * @return The metadata, empty when the device is not initialized.
     */
    const DeviceMetadata& metadata() const;

    /**
     * @brief Checks whether the device is fully configured and usable.
     *
     * A device becomes valid once init() has built a kinematic chain with at
     * least a base link.
     *
     * @return true when the device is usable.
     */
    virtual bool isValid() const
    {
        return is_valid_;
    }

    /**
     * @brief Configures the device from definition data (takes ownership).
     *
     * After init() the definition is immutable; the device owns it and builds
     * its link / joint views, ends and the coordinate-frame tree from it.
     *
     * @param data The device definition data.
     * @throws std::logic_error when the definitions are invalid (missing base
     *         link, joint referencing a null link, multiple parents, ...).
     */
    virtual void init(std::unique_ptr<DeviceData> data);

    /**
     * @brief Returns the device definition data (non-owning).
     *
     * @return The definition data, or null when not initialized.
     */
    const DeviceData* data() const
    {
        return owned_data_.get();
    }

    /**
     * @brief Returns the device's named material library.
     *
     * Visuals reference these materials by name.
     *
     * @return The materials, empty when the device is not initialized.
     */
    const std::vector<DeviceMaterial>& materials() const
    {
        static const std::vector<DeviceMaterial> s_empty;
        return owned_data_ ? owned_data_->materials : s_empty;
    }

    /**
     * @brief Returns the links of the kinematic chain (chain order).
     *
     * @return The links, non-owning views.
     */
    std::vector<raw_ptr<Link>> links() const
    {
        return links_;
    }

    /**
     * @brief Returns the joints of the kinematic chain (chain order).
     *
     * @return The joints, non-owning views.
     */
    std::vector<raw_ptr<Joint>> joints() const
    {
        return joints_;
    }

    /**
     * @brief Returns the base link.
     *
     * @return The base link, or null when the device is invalid.
     */
    raw_ptr<Link> baseLink() const
    {
        return links_.empty() ? nullptr : links_.front();
    }

    /**
     * @brief Returns the number of end frames.
     *
     * @return The end count.
     */
    std::size_t getNumEnds() const
    {
        return ends_.size();
    }

    /**
     * @brief Returns all end frames.
     *
     * @return The end frames, non-owning views.
     */
    std::vector<raw_ptr<kinematics::Frame>> getEnds() const
    {
        return ends_;
    }

    /**
     * @brief Returns the end frame at the given index.
     *
     * @param index The end index.
     * @return The end frame, or null when out of range.
     */
    raw_ptr<kinematics::Frame> getEnd(std::size_t index) const
    {
        return index < ends_.size() ? ends_[index] : nullptr;
    }

    /**
     * @brief Returns the device's joint values from a scene state.
     *
     * @param state The scene state.
     * @return The joint values, empty when the device is not registered in
     *         the state.
     */
    kinematics::Q getQ(const kinematics::State& state) const;

    /**
     * @brief Writes the device's joint values into a scene state.
     *
     * @param q The joint values; its size must match the device dof.
     * @param state The scene state to write into.
     * @throws std::invalid_argument when q.size() differs from the device
     *         dof.
     */
    void setQ(const kinematics::Q& q, kinematics::State& state);

  protected:
    /**
     * @brief Takes ownership of the definition and generates the intermediate
     *        data (link / joint views, ends, frame tree).
     *
     * Called exactly once by init(); re-init releases the previous ownership.
     *
     * @param data The device definition data.
     * @throws std::logic_error when the definitions are invalid.
     */
    void initDevice(std::unique_ptr<DeviceData> data);

    /**
     * @brief Sets the device kind.
     *
     * @param kind The new kind.
     */
    void setDeviceKind(DeviceKind kind)
    {
        device_kind_ = kind;
    }

  private:
    DeviceKind                              device_kind_{ DeviceKind::Other };
    std::filesystem::path                   file_path_;
    std::unique_ptr<DeviceData>             owned_data_;
    std::vector<raw_ptr<Link>>              links_;
    std::vector<raw_ptr<Joint>>             joints_;
    std::vector<raw_ptr<kinematics::Frame>> ends_;
    bool                                    is_valid_{ false };
};

V_ROBOTICS_WORKCELL_NS_END
