add_subdirectory(global)
add_subdirectory(core)
add_subdirectory(async)
add_subdirectory(math)
add_subdirectory(geometry)
add_subdirectory(iobase)
add_subdirectory(runtime)
add_subdirectory(system)
add_subdirectory(window)
add_subdirectory(crypto)
add_subdirectory(progress)
add_subdirectory(logging)